import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" type="text/css" href="fonts/fonts.css" />
  
  <link rel="stylesheet" type="text/css" href="/assets/fonts/font-icons.css" />
  <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="/assets/css/swiper-bundle.min.css" />
  <link rel="stylesheet" type="text/css" href="/assets/css/animate.css" />
  {/* <link rel="stylesheet" type="text/css" href="../../../sibforms.com/forms/end-form/build/sib-styles.css" /> */}
  <link rel="stylesheet" type="text/css"  href="/assets/css/styles.css"/>
   <link rel="shortcut icon" href="/assets/images/logo/favicon.png" />
   <link rel="apple-touch-icon-precomposed" href="/assets/images/logo/favicon.png"></link>
     
      <Head>
       
    </Head>
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Script src="/assets/js/jquery.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/bootstrap.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/bootstrap-select.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/swiper-bundle.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/lazysize.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/count-down.js" strategy="lazyOnload" />
        <Script src="/assets/js/carousel.js" strategy="lazyOnload" />
        <Script src="/assets/js/wow.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/multiple-modal.js" strategy="lazyOnload" />
        <Script src="/assets/js/main.js" strategy="lazyOnload" />
      </body>
      
    </html>
  );
}
